eureka:
  instance:
    prefer-ip-address: false
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      circuitBreaker:
      # Short circuit after reaching this number of failures in the configuration time window. Default 20
      requestVolumeThreshold: 1
      # The time value of the trigger short circuit. When the value is set to 5000, the request will be rejected within 5000 milliseconds after the circuit break is triggered.
      # It is 5000 milliseconds before the circuit is closed. Default 5000
      sleepWindowInMilliseconds: 15000
      # Forced to open the fuse, if this switch is turned on, then reject all requests, default false
      forceOpen: false
      # Forced to close the fuse If this switch is turned on, the circuit will always be off and ignored, the default is false
      forceClosed: false
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
hibernate:
  maxShared: 1
  maxReceivingShared: 100
  queryThreshold: 100
spring:
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  metrics:
    export:
      prometheus:
        enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000